Adapting stub generation from MSMPI to MPICH2, so it won't be necessary to put up the include files in this git repo.

diff --git a/genMPICH2stubs b/genMPICH2stubs
--- a/genMPICH2stubs
+++ b/genMPICH2stubs
@@ -29,6 +29,71 @@
 #
 #------------------------------------------------------------------------------
 
+#set up variables
+MPIVERSION=`echo $FOAM_MPI | sed 's=mpich2\-=='`
+INSTPACK_URL="http://www.mcs.anl.gov/research/projects/mpich2/downloads/tarballs/$MPIVERSION"
+INSTPACK_X86="$FOAM_MPI-win-ia32.msi"
+INSTPACK_X86_64="$FOAM_MPI-win-x86-64.msi"
+
+if [ "x$WM_ARCH_OPTION" = "x64" ]; then
+  INSTPACK_FILE=$INSTPACK_X86_64
+else
+  INSTPACK_FILE=$INSTPACK_X86
+fi
+
+export PATH=$PATH:$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER$WM_COMPILER_ARCH/pexports-0.44-1/bin
+
+if ! isMinGW; then
+  echo "Error: this script is meant to be used for MinGW compilers only!"
+  exit 1
+fi
+
+# run from third-party directory only
+cd ${0%/*} || exit 1
+wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
+    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    The environment variables are inconsistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+. etc/tools/makeExtraThirdPartyFunctions
+
+
+#end of initializations -------------------------------------------
+
+
+download_files()
+{
+  # Make sure wget is installed
+  if test "x`which wget`" = "x" ; then
+    echo "You need to install wget."
+    exit 1
+  fi
+
+  downloadFile $INSTPACK_FILE $INSTPACK_URL/$INSTPACK_FILE
+}
+
+
+unpack_files()
+{
+  echo "Unpacking files..."
+
+  rm $SRCDIR/*
+  7z x $DownloadRepository/$INSTPACK_FILE -o$SRCDIR/ product.cab
+  cd $SRCDIR
+  7z x product.cab mpi*.h msmpi.dll
+
+}
+
+
+must_build_pexports()
+{
+  cd $WM_THIRD_PARTY_DIR
+  ./build-pexports
+}
+
+
 function copy_and_link_mpich2
 {
   cd "$BUILDDIR"
@@ -48,6 +113,7 @@ function copy_and_link_mpich2
   fi
 }
 
+
 function create_gcccompatible_library
 {
   echo -e "\033[1m creating mpi.a \033[0m"
@@ -55,6 +121,7 @@ function create_gcccompatible_library
   cd $BUILDDIR/lib
   $WM_DLLTOOL -d ../mpich2.def -l libmpi.a -D MPICH2MPI.DLL
 }
+
 
 function patch_mpi_includes
 {
@@ -81,12 +148,15 @@ echo '--- orig/include/mpi.h  2009-08-06 16:11:46.000000000 +0100
   fi
 }
 
+
 function cleanup
 {
   if [ -n "$BUILDDIR" -a -e "$BUILDDIR" ]; then
     rm -rf "$BUILDDIR"
   fi
 }
+
+
 
 #script start ------------------------------------------------------
 
@@ -95,34 +165,51 @@ if isMinGW; then
   BUILDDIR="$MPI_ARCH_PATH"
   SRCDIR="$MPI_HOME/source"
   
- if [ $# -eq 1 -a "$1" = "clean" ]; then
+  if [ $# -eq 1 -a "$1" = "clean" ]; then
 
-  echo -e "\033[1m Cleaning up MPICH2 stub... \033[0m"
-  cleanup
-
- else
-
-  echo -e "\033[1m Generating MPICH2 stub... \033[0m"
-
-  mkdir -p "$BUILDDIR"
-  
-  if [ -d "$SRCDIR" ]; then
-
-    if [ ! -e "$BUILDDIR/lib/libmpi.a" ]; then
-      copy_and_link_mpich2
-      create_gcccompatible_library
-      patch_mpi_includes
-      echo -e "\033[1m All done. \033[0m"
-    else
-      echo -e "\033[1m MPICH2 stub is already built and ready to use. \033[0m"
-    fi
+    echo -e "\033[1m Cleaning up MPICH2 stub... \033[0m"
+    cleanup
 
   else
-    echo -e "\033[1m Failed to complete, due to lack of folder $SRCDIR \033[0m"
+
+    if test -z "x`which 7z`" ; then
+      echo "Please install 7zip. In Ubuntu, the package name is p7zip-full."
+      echo "If 7zip isn't available for your Linux distribution, please go to www.7zip.org to download the generic version."
+      exit 1
+    fi
+
+    mkdir -p "$BUILDDIR"
+    if [ ! -d "$SRCDIR" ]; then mkdir -p "$SRCDIR"; fi
+
+    if [ -d "$SRCDIR" ]; then
+
+      if [ ! -e "$BUILDDIR/lib/libmpi.a" ]; then
+
+        echo -e "\033[1m Downloading necessary MPICH2 installation files...\033[0m"
+        download_files
+
+        echo -e "\033[1m Unpacking necessary MPICH2 installation files...\033[0m"
+        unpack_files
+
+        if test "x`which pexports`" = "x" ; then
+          must_build_pexports
+        fi
+
+        echo -e "\033[1m Generating MPICH2 stub... \033[0m"
+
+        copy_and_link_mpich2
+        create_gcccompatible_library
+        patch_mpi_includes
+        echo -e "\033[1m All done. \033[0m"
+      else
+        echo -e "\033[1m MPICH2 stub is already built and ready to use. \033[0m"
+      fi
+
+    else
+      echo -e "\033[1m Failed to complete, due to lack of folder $SRCDIR \033[0m"
+    fi
+
+    cd $WM_THIRD_PARTY_DIR
+
   fi
-
-  cd $WM_THIRD_PARTY_DIR
-
- fi
-
 fi
diff --git a/genMSMPIstubs b/genMSMPIstubs
--- a/genMSMPIstubs
+++ b/genMSMPIstubs
@@ -90,11 +90,13 @@ unpack_files()
 
 }
 
+
 must_build_pexports()
 {
   cd $WM_THIRD_PARTY_DIR
   ./build-pexports
 }
+
 
 function copy_and_link_msmpi
 {
@@ -117,6 +119,7 @@ function create_gcccompatible_library
   WM_DLLTOOL=`echo $WM_CC | sed s/gcc/dlltool/`
   $WM_DLLTOOL -d libmpi.def -l libmpi.a -D msmpi.dll
 }
+
 
 function patch_mpi_includes
 {
@@ -155,6 +158,7 @@ echo '--- mpi.h_orig  2011-01-18 15:11:38.284485101 +0000
 
 }
 
+
 function cleanup
 {
   if [ -n "$BUILDDIR" -a -e "$BUILDDIR" ]; then
@@ -169,51 +173,51 @@ if isMinGW; then
   BUILDDIR="$MPI_ARCH_PATH"
   SRCDIR="$MPI_HOME/source"
 
- if [ $# -eq 1 -a "$1" = "clean" ]; then
+  if [ $# -eq 1 -a "$1" = "clean" ]; then
 
-  echo -e "\033[1m Cleaning up MSMPI stub... \033[0m"
-  cleanup
-
- else
-
-  if test -z "x`which 7z`" ; then
-    echo "Please install 7zip. In Ubuntu, the package name is p7zip-full."
-    echo "If 7zip isn't available for your Linux distribution, please go to www.7zip.org to download the generic version."
-    exit 1
-  fi
-
-  mkdir -p "$BUILDDIR"
-  if [ ! -d "$SRCDIR" ]; then mkdir -p "$SRCDIR"; fi
-
-  if [ -d "$SRCDIR" ]; then
-
-    if [ ! -e "$BUILDDIR/lib/libmpi.a" ]; then
-
-      echo -e "\033[1m Downloading necessary MSMPI installation files...\033[0m"
-      download_files
-
-      echo -e "\033[1m Unpacking necessary MSMPI installation files...\033[0m"
-      unpack_files
-
-      if test "x`which pexports`" = "x" ; then
-        must_build_pexports
-      fi
-
-      echo -e "\033[1m Generating MSMPI stub... \033[0m"
-
-      copy_and_link_msmpi
-      create_gcccompatible_library
-      patch_mpi_includes
-      echo -e "\033[1m All done. \033[0m"
-    else
-      echo -e "\033[1m MSMPI stub is already built and ready to use. \033[0m"
-    fi
+    echo -e "\033[1m Cleaning up MSMPI stub... \033[0m"
+    cleanup
 
   else
-    echo -e "\033[1m Failed to complete, due to lack of folder $SRCDIR \033[0m"
+
+    if test -z "x`which 7z`" ; then
+      echo "Please install 7zip. In Ubuntu, the package name is p7zip-full."
+      echo "If 7zip isn't available for your Linux distribution, please go to www.7zip.org to download the generic version."
+      exit 1
+    fi
+
+    mkdir -p "$BUILDDIR"
+    if [ ! -d "$SRCDIR" ]; then mkdir -p "$SRCDIR"; fi
+
+    if [ -d "$SRCDIR" ]; then
+
+      if [ ! -e "$BUILDDIR/lib/libmpi.a" ]; then
+
+        echo -e "\033[1m Downloading necessary MSMPI installation files...\033[0m"
+        download_files
+
+        echo -e "\033[1m Unpacking necessary MSMPI installation files...\033[0m"
+        unpack_files
+
+        if test "x`which pexports`" = "x" ; then
+          must_build_pexports
+        fi
+
+        echo -e "\033[1m Generating MSMPI stub... \033[0m"
+
+        copy_and_link_msmpi
+        create_gcccompatible_library
+        patch_mpi_includes
+        echo -e "\033[1m All done. \033[0m"
+      else
+        echo -e "\033[1m MSMPI stub is already built and ready to use. \033[0m"
+      fi
+
+    else
+      echo -e "\033[1m Failed to complete, due to lack of folder $SRCDIR \033[0m"
+    fi
+
+    cd $WM_THIRD_PARTY_DIR
+
   fi
-
-  cd $WM_THIRD_PARTY_DIR
-
- fi
 fi
