Multiple fixes to MPICH2 and MSMPI stub generation. Library interface creation for Open-MPI created for MinGW.

diff --git a/genMSMPIstubs b/genMSMPIstubs
--- a/genMSMPIstubs
+++ b/genMSMPIstubs
@@ -113,7 +113,7 @@ function copy_and_link_msmpi
 
 function create_gcccompatible_library
 {
-  echo -e "\033[1m creating mpi.a \033[0m"
+  echo -e "\033[1m creating libmpi.a \033[0m"
   cd lib
   pexports -o msmpi.dll > libmpi.def
   WM_DLLTOOL=`echo $WM_CC | sed s/gcc/dlltool/`
@@ -176,56 +176,53 @@ function cleanup
 
 #script start ------------------------------------------------------
 
-if isMinGW; then
+BUILDDIR="$MPI_ARCH_PATH"
+SRCDIR="$MPI_HOME/source"
 
-  BUILDDIR="$MPI_ARCH_PATH"
-  SRCDIR="$MPI_HOME/source"
+if [ $# -eq 1 -a "$1" = "clean" ]; then
 
-  if [ $# -eq 1 -a "$1" = "clean" ]; then
+  echo -e "\033[1m Cleaning up MSMPI stub... \033[0m"
+  cleanup
 
-    echo -e "\033[1m Cleaning up MSMPI stub... \033[0m"
-    cleanup
+else
 
-  else
+  if test -z "x`which 7z`" ; then
+    echo "Please install 7zip. In Ubuntu, the package name is p7zip-full."
+    echo "If 7zip isn't available for your Linux distribution, please go to www.7zip.org to download the generic version."
+    exit 1
+  fi
 
-    if test -z "x`which 7z`" ; then
-      echo "Please install 7zip. In Ubuntu, the package name is p7zip-full."
-      echo "If 7zip isn't available for your Linux distribution, please go to www.7zip.org to download the generic version."
-      exit 1
-    fi
+  mkdir -p "$BUILDDIR"
+  if [ ! -d "$SRCDIR" ]; then mkdir -p "$SRCDIR"; fi
 
-    mkdir -p "$BUILDDIR"
-    if [ ! -d "$SRCDIR" ]; then mkdir -p "$SRCDIR"; fi
+  if [ -d "$SRCDIR" ]; then
 
-    if [ -d "$SRCDIR" ]; then
+    if [ ! -e "$BUILDDIR/lib/libmpi.a" ]; then
 
-      if [ ! -e "$BUILDDIR/lib/libmpi.a" ]; then
+      echo -e "\033[1m Downloading necessary MSMPI installation files...\033[0m"
+      download_files
 
-        echo -e "\033[1m Downloading necessary MSMPI installation files...\033[0m"
-        download_files
+      echo -e "\033[1m Unpacking necessary MSMPI installation files...\033[0m"
+      unpack_files
 
-        echo -e "\033[1m Unpacking necessary MSMPI installation files...\033[0m"
-        unpack_files
-
-        if test "x`which pexports`" = "x" ; then
-          must_build_pexports
-        fi
-
-        echo -e "\033[1m Generating MSMPI stub... \033[0m"
-
-        copy_and_link_msmpi
-        create_gcccompatible_library
-        patch_mpi_includes
-        echo -e "\033[1m All done. \033[0m"
-      else
-        echo -e "\033[1m MSMPI stub is already built and ready to use. \033[0m"
+      if test "x`which pexports`" = "x" ; then
+        must_build_pexports
       fi
 
+      echo -e "\033[1m Generating MSMPI stub... \033[0m"
+
+      copy_and_link_msmpi
+      create_gcccompatible_library
+      patch_mpi_includes
+      echo -e "\033[1m All done. \033[0m"
     else
-      echo -e "\033[1m Failed to complete, due to lack of folder $SRCDIR \033[0m"
+      echo -e "\033[1m MSMPI stub is already built and ready to use. \033[0m"
     fi
 
-    cd $WM_THIRD_PARTY_DIR
-
+  else
+    echo -e "\033[1m Failed to complete, due to lack of folder $SRCDIR \033[0m"
   fi
+
+  cd $WM_THIRD_PARTY_DIR
+
 fi
diff --git a/genOPENMPIstubs b/genOPENMPIstubs
--- a/genOPENMPIstubs
+++ b/genOPENMPIstubs
@@ -25,9 +25,67 @@
 #
 # Description
 #     This script generates the link library and prepares the include 
-#   files for Open-MPI.
+#   files for the pre-built version of Open-MPI for Windows.
 #
 #------------------------------------------------------------------------------
 
-#do nothing for now...
-exit 0
+if ! isMinGW; then
+  echo "Error: this script is meant to be used for MinGW compilers only!"
+  exit 1
+fi
+
+# run from third-party directory only
+cd ${0%/*} || exit 1
+wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
+    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
+    echo "    The environment variables are inconsistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+}
+. etc/tools/ThirdPartyFunctions
+. etc/tools/makeExtraThirdPartyFunctions
+
+export PATH=$PATH:$WM_THIRD_PARTY_DIR/platforms/$WM_ARCH$WM_COMPILER$WM_COMPILER_ARCH/pexports-0.44-1/bin
+
+#end of initializations -------------------------------------------
+
+
+must_build_pexports()
+{
+  cd $WM_THIRD_PARTY_DIR
+  ./build-pexports
+}
+
+
+function create_gcccompatible_library
+{
+  echo -e "\033[1m creating libmpi.a \033[0m"
+  WM_DLLTOOL=`echo $WM_CC | sed s/gcc/dlltool/`
+  cd $MPI_ARCH_PATH/lib
+  pexports -o $MPI_ARCH_PATH/bin/libmpi.dll > openmpi.def
+  $WM_DLLTOOL -d openmpi.def -l libmpi.a -D libmpi.dll
+}
+
+
+#script start ------------------------------------------------------
+if [ ! -e "$MPI_ARCH_PATH/bin/libmpi.dll" ]; then
+  ./get-em so openmpi-win=default || {
+    echo "Unable to retrieve and unpack necessary files for Open-MPI."
+    exit 1
+  }
+fi
+
+if [ ! -e "$MPI_ARCH_PATH/lib/libmpi.a" ]; then
+
+  if test "x`which pexports`" = "x" ; then
+    must_build_pexports
+  fi
+
+  echo -e "\033[1m Generating Open-MPI library interfaces for MinGW... \033[0m"
+
+  create_gcccompatible_library
+  #patch_mpi_includes
+  echo -e "\033[1m All done. \033[0m"
+else
+  echo -e "\033[1m Open-MPI library interfaces for MinGW are already built and ready to use. \033[0m"
+fi
