Adapted changes that were made for blueCFD 2.1-2.

diff --git a/makeMinGWGcc b/makeMinGWGcc
--- a/makeMinGWGcc
+++ b/makeMinGWGcc
@@ -40,6 +40,10 @@ wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
 }
 . etc/tools/ThirdPartyFunctions
 . etc/tools/makeExtraThirdPartyFunctions
+
+#Source buildLogs helper stuff
+. $WM_PROJECT_DIR/bin/tools/BuildLogFunctions
+
 #------------------------------------------------------------------------------
 
 usage() {
@@ -95,7 +99,7 @@ W32APIVERSION=`. etc/defaults.sh ; echo \$w32api_version`
 MINGW_W64_VERSION=`. etc/defaults.sh ; echo \$mingw_w64_version`
 
 #LOG FOLDER
-LOG_FOLDER="$WM_THIRD_PARTY_DIR/../buildLogs"
+LOG_FOLDER="$BUILD_LOG_FOLDER"
 
 #-----------------------------------------------------
 #
@@ -183,10 +187,11 @@ MINGW32RT_BDIR="$buildBASE/$MINGW32RTVERSION"
 W32API_BDIR="$buildBASE/$W32APIVERSION"
 
 MINGW_W64_BDIR="$buildBASE/mingw-w64-crt-$MINGW_W64_VERSION"
+GENDEF_BDIR="$buildBASE/gendef-$MINGW_W64_VERSION"
 
 
 # Make sure these are initialized as we want them
-GCC_LANGS="c,c++"
+GCC_LANGS="c,c++,fortran"
 
 
 
@@ -255,6 +260,23 @@ get_em_all()
       fi
       ;;
   esac
+}
+
+
+do_unlinks_GM()
+{
+  #hook up gmp, mpfr and mpc to gcc's folder
+  if [ -L "$GCC_HOME/gmp" ]; then
+    unlink $GCC_HOME/gmp
+  fi
+  if [ -L "$GCC_HOME/mpfr" ]; then
+    unlink $GCC_HOME/mpfr
+  fi
+  if [ -n "$MPCVERSION" ]; then
+    if [ -L "$GCC_HOME/mpc" ]; then
+      unlink $GCC_HOME/mpc
+    fi
+  fi
 }
 
 
@@ -550,6 +572,47 @@ install_gcc()
 }
 
 
+configure_gendef()
+{
+  [ -d "$GENDEF_BDIR" ] && rm -rf "$GENDEF_BDIR"
+  mkdir -p "$GENDEF_BDIR"
+  cd "$GENDEF_BDIR"
+  echo "Configuring gendef"
+  "$MINGW_W64_HOME/mingw-w64-tools/gendef/configure" --prefix=${PREFIX} \
+      $CONFIGHOST \
+      > ${LOG_FOLDER}/gendef-${WM_COMPILER}_configure.log  2>&1
+  if test $? -ne 0; then
+    echo "make of binutils failed - log available: ${LOG_FOLDER}/gendef-${WM_COMPILER}_configure.log"
+    exit 1
+  fi
+}
+
+
+build_gendef()
+{
+  cd "$GENDEF_BDIR"
+  echo "Building gendef"
+  make -j $WM_NCOMPPROCS CFLAGS="-O2" LDFLAGS="-s" > \
+    ${LOG_FOLDER}/gendef-${WM_COMPILER}_make.log 2>&1
+  if test $? -ne 0; then
+    echo "make of gendef failed - log available: ${LOG_FOLDER}/gendef-${WM_COMPILER}_make.log"
+    exit 1
+  fi
+}
+
+
+install_gendef()
+{
+  cd "$GENDEF_BDIR"
+  echo "Installing gendef"
+  make install > ${LOG_FOLDER}/gendef-${WM_COMPILER}_make-install.log 2>&1
+  if test $? -ne 0; then
+    echo "install of gendef failed - log available: ${LOG_FOLDER}/gendef-${WM_COMPILER}_make-install.log"
+    exit 1
+  fi
+}
+
+
 createSTDCPPShared()
 {
   cd "${PREFIX}/mingw/lib"
@@ -612,9 +675,25 @@ final_tweaks()
   else #if [ $CROSS4WIN -eq 1 ]; then
 
     cd ${PREFIX}/bin
-    for afile in windres.exe dlltool.exe; do
-      ln -s $afile ${TARGET}-$afile
+    for afile in *.exe; do
+      case $afile in
+        ${TARGET}*.exe) ;;
+        *)
+          #generate stub shell script
+          echo "#\!/bin/sh" > ${TARGET}-${afile%%.*}
+          echo "$afile \$*" >> ${TARGET}-${afile%%.*}
+          chmod +x ${TARGET}-${afile%%.*}
+
+          #generate stub batch file
+          echo "@echo off" > ${TARGET}-${afile%%.*}.bat
+          echo "$afile %*" >> ${TARGET}-${afile%%.*}.bat
+        ;;
+      esac
     done
+
+    #fix the float.h issue
+    cd $WM_THIRD_PARTY_DIR
+    ./fixSystemMingw force4win
 
   fi
 
@@ -628,6 +707,7 @@ final_tweaks()
 
 get_em_all
 
+do_unlinks_GM
 do_links_GM
 
 configure_binutils
@@ -659,6 +739,10 @@ if [ $CROSS4WIN -eq 0 ]; then
 
     build_gcc
     install_gcc
+
+    configure_gendef
+    build_gendef
+    install_gendef
     ;;
   esac
 
@@ -682,6 +766,10 @@ else #cross-compile native compiler for Windows
     install_gcc
 
     copy_mingw_w64_crt
+
+    configure_gendef
+    build_gendef
+    install_gendef
     ;;
   esac
 
